strictness: veryhigh
doc-warnings: true
pep8:
    full: true
    disable:
        - D202
        - D203
        - D100
        - N803
        - N802
        - N806
        - N813
pylint:
    disable:
        - D100
        - unused-argument
        - invalid-name
        - relative-import
        - too-many-public-methods
        - too-many-instance-attributes
        - too-many-locals
        - too-many-arguments
        - unused-variable
        - too-many-statements
        - too-many-return-statements
