strictness: veryhigh
doc-warnings: true
pep8:
    full: true
pylint:
    disable:
        - r0913
        - unused-argument
        - invalid-name
        - relative-import
        - too-many-public-methods
        - too-many-instance-attributes
        - N803
